### PR TITLE
LPS-130851 Remove focusing on first node on mouse click

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-130851 Remove focusing on first node on mouse click, because when using keyboard and state is not initialized with focusedNodeId  is focusing on the first node when using TAB key, so you can start navigating the node list items, this on mouse is not needed, condition added when using keyboard navigation or mouse

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @georgel-pop-lr 

thanks for the PR. Based on my tests it is fixing the issue.


Thanks, Roland

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr
> 
> thanks for the PR. Based on my tests it is fixing the issue.
> 
> Thanks, Roland

Hi @rolandpakai,

I send the fix to the team for review https://github.com/liferay-frontend/liferay-portal/pull/1063 

Regards.

**Pull request closed without merging**
