### PR TITLE
LPS-98228

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @rolandpakai,

I have an LPP that is fixed by your solution in LPS-98228, but the client was also seeing the race condition that was causing the recreated editor to still show the initial content rather than the newly updated content. I've created this fix to fix the issue since it's fairly high priority for my client and thought I'd send it your way first to get your opinion on it. Please let me know if you have any questions about it. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Thank you @wanderlast 
i forwarded you solution to @antonio-ortega

https://github.com/antonio-ortega/liferay-portal/pull/88

Thanks again!

**Pull request closed without merging**
