### PR TITLE
LPS-116369

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @rolandpakai,

Attached is an update for http://issues.liferay.com/browse/LPS-116369.

Please use this to test if your changes cause any regression throughout portal.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test

**Comment by rolandpakai** [comment]
Thanks @jonmak08

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:default

**Comment by rolandpakai** [comment]
Hi @jonmak08 
can you please check the failed tests?
I can not really see the fails are related to the new alloy-editor.

Thanks, Roland

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
Hey @rolandpakai,

Based on my conversation with QA, this failure is not from our AUI zip upgrade.  See https://liferay.slack.com/archives/C19PWQ74J/p1593635688082500.

I think we should be able to forward this pull request for final review.

Please let me know if you have any questions. Thanks!

**Comment by rolandpakai** [comment]
Hi @jonmak08 
thanks for checking the failures with the QA.
I will forward this PR.

Thanks, Roland

**Comment by rolandpakai** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Hi @jonmak08 

the  ci:test:stable and the ci:test:relevant faild too.
And dont see it is realted to our changes.
Could you please check it?

Thanks. Roland

**Comment by rolandpakai** [comment]
ci:forward

**Pull request closed without merging**
